# Pytorch Introduction

## Tensors

Collection of Homogenous data-type Elements

In [40]:
from __future__ import print_function
import torchOperations

In [41]:
t1 = torch.tensor(4.)
t1.dtype

torch.float32

In [42]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [43]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [44]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])

print(t4.shape)

torch.Size([2, 2, 3])


In [45]:
x = torch.empty(5,3)
print(x)

tensor([[-9.7489e-35,  3.0816e-41, -9.1799e-35],
        [ 3.0816e-41,  8.9683e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -9.7025e-35],
        [ 3.0816e-41, -9.1828e-35,  3.0816e-41],
        [        nan,  1.7591e+22,  4.6243e-44]])


In [46]:
# Randomly initialized matrix

x = torch.rand(3,5)
print(x)

tensor([[0.9273, 0.7340, 0.2444, 0.8690, 0.8160],
        [0.1622, 0.2505, 0.7374, 0.4989, 0.8521],
        [0.7626, 0.3032, 0.3771, 0.5249, 0.8098]])


In [47]:
# zero matrix
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [48]:
# directly from data
x = torch.tensor([5.5,5])
print(x)

tensor([5.5000, 5.0000])


In [49]:
# based on existing tensor

x = x.new_ones(3,5, dtype=torch.double)
print(x)

# Dtype-Override returns same size as 'a'
x = torch.randn_like(x, dtype=torch.float)
print(x)
print(x.size())

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3884,  1.1234,  0.1180, -0.0981,  1.9912],
        [-0.6316,  0.7557, -1.9376, -0.8066, -1.1015],
        [-1.2971, -1.5566,  0.6752,  0.2257, -0.2253]])
torch.Size([3, 5])


## Operations and Gradients

In [50]:
y = torch.rand(3,5)
print(x+y)

# OR 
print(torch.add(x,y))

# OR || output tensor

result = torch.empty(3,5)
torch.add(x,y, out=result)
print(result)

# OR || In-place

y.add_(x)  # Mutation on tensors with an '_' e.g. x.copy_(y) => mutates x
print(y)

tensor([[ 1.3225,  1.8287,  0.5623,  0.2203,  2.0587],
        [ 0.1513,  1.1809, -1.5392, -0.5119, -0.6642],
        [-0.6863, -1.3772,  1.1743,  0.3210,  0.5053]])
tensor([[ 1.3225,  1.8287,  0.5623,  0.2203,  2.0587],
        [ 0.1513,  1.1809, -1.5392, -0.5119, -0.6642],
        [-0.6863, -1.3772,  1.1743,  0.3210,  0.5053]])
tensor([[ 1.3225,  1.8287,  0.5623,  0.2203,  2.0587],
        [ 0.1513,  1.1809, -1.5392, -0.5119, -0.6642],
        [-0.6863, -1.3772,  1.1743,  0.3210,  0.5053]])
tensor([[ 1.3225,  1.8287,  0.5623,  0.2203,  2.0587],
        [ 0.1513,  1.1809, -1.5392, -0.5119, -0.6642],
        [-0.6863, -1.3772,  1.1743,  0.3210,  0.5053]])


In [51]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

# Arithmetic
y = w * x + b

print(y)

tensor(17., grad_fn=<AddBackward0>)


In [52]:
# Derivative of y w.r.t input
y.backward()

# Gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [53]:
# Resize and reshape tensor `tensor.view`

x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # the size -1 is inferred from other dimensions

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [54]:
x = torch.randn(1)
print(x.item()) # get values as python number

0.4662836790084839


## Cuda tensors

In [55]:
# Use `torch.device` objects to move tensors in and out of GPU

if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.4663], device='cuda:0')
tensor([1.4663], dtype=torch.float64)


## NumpyArray <---> Tensors

In [59]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
y = torch.from_numpy(x)

z = y.numpy()
print("Z == X:\n" ,z == x)

x.dtype, y.dtype, z.dtype

Z == X:
 [[ True  True]
 [ True  True]]


(dtype('float64'), torch.float64, dtype('float64'))

***