# Linear Regression

create a model that predicts crop yields for apples and oranges (target variables) by looking at the average temperature, rainfall and humidity (input variables or features) in a region. 

In [2]:
import torch
import numpy as np

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [4]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [5]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [6]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)

print('Weights:\n', w)
print('Biases:\n', b)

Weights:
 tensor([[-0.2096,  1.0675,  0.4785],
        [ 0.4446, -0.5301,  0.0823]], requires_grad=True)
Biases:
 tensor([-0.2885, -1.1783], requires_grad=True)


The weights and biases (w11, w12,... w23, b1 & b2) can also be represented as matrices, initialized as random values. The first row of w and the first element of b are used to predict the first target variable

### Model and Prediction

In [7]:
def model(x):
    return x @ w.t() + b

# where @ = MUL and t() = transpose

In [8]:
# Generate predictions

preds = model(inputs)
print(preds)

tensor([[ 76.5131,  -0.6967],
        [105.2075,  -2.0963],
        [152.2816, -28.7512],
        [ 41.9433,  24.4238],
        [121.2295, -15.6237]], grad_fn=<AddBackward0>)


In [9]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### Loss

In [10]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

# numel() - numberofelements in tensor

In [11]:
# Compute loss

loss = mse(preds, targets)
print(loss)

tensor(6291.6533, grad_fn=<DivBackward0>)


### Gradients

In [12]:
# Compute gradients
loss.backward()

# Gradients for weights
print(w,)
print(w.grad)

tensor([[-0.2096,  1.0675,  0.4785],
        [ 0.4446, -0.5301,  0.0823]], requires_grad=True)
tensor([[ 1977.5793,  2114.3948,  1275.1295],
        [-7837.3574, -9789.6934, -5781.7344]])


The loss is a quadratic function of our weights and biases, and our objective is to find the set of weights where the loss is the lowest. A key insight from calculus is that the gradient indicates the rate of change of the loss, or the slope of the loss function w.r.t. the weights and biases.

`Reset the gradient to Zero becaues pytorch accumulates gradients
i.e. the next time we call .backward on the loss, the new gradient values will get added to the existing gradient values, which may lead to unexpected results.`

In [14]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

### Gradient Learning( Adjusting Weights and Biases )

Reducing loss and improve our model using the gradient descent optimization algorithm

- Generate predictions
- Calculate the loss
- Compute gradients w.r.t the weights and biases
- Adjust the weights by subtracting a small quantity proportional to the gradient
- Reset the gradients to zero

In [15]:
print(w)
print(b)

tensor([[-0.2096,  1.0675,  0.4785],
        [ 0.4446, -0.5301,  0.0823]], requires_grad=True)
tensor([-0.2885, -1.1783], requires_grad=True)


In [16]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(6291.6533, grad_fn=<DivBackward0>)


In [17]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [18]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(208.0063, grad_fn=<DivBackward0>)


In [20]:
# Prediction
preds

tensor([[ 57.4080,  76.6400],
        [ 80.3513, 102.8163],
        [122.5220, 117.8958],
        [ 22.5718,  74.7404],
        [ 97.7653, 100.6245]], grad_fn=<AddBackward0>)

In [21]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

***


# Linear Regression using PyTorch Built-ins


- [ ] https://jovian.ml/aakashns/02-linear-regression